---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-documentdb-reader
  namespace: default
rules:
- apiGroups:
  - documentdb.services.k8s.aws
  resources:
  verbs:
  - get
  - list
  - watch
